INHERIT: !ENV MKDOCS_NUMTIDE_THEME

### Site metadata ###

site_name: SrvOS
site_description: NixOS profiles for servers
site_url: https://nix-community.github.io/srvos/
repo_name: 'nix-community/srvos'
repo_url: &repo_url https://github.com/nix-community/srvos
edit_uri: edit/main/docs

### Extra variables

extra:
  repo_url: *repo_url
